### ISSUE TITLE
my congratulations to 2.14.0

### ISSUE THREAD

**Issue by uvwild** [mojohaus/versions#868] opened 2022-12-19 17:31 UTC
just to share.

On Dec 14.  the release of 2.14.0 broke our pipeline and the development team came to a halt!
Due to the complexity of our CICD system the cause was not obvious at first.

I discovered soon that the  bug was caused by the non intuitive approach of placing the reactor next to the modules instead of on top. Obviously, not the way to standard way to go and why nobody noticed that issue before the release of 2.14.0.
But there are always people that want it their way.

My workaround was to refactor the Reaktor structure in the pipeline before the build, so I extended our pipeline to do so.
and  when it worked version release the version release 2.14.1 came out ;)  yeah, 2 nights for nothing

So thank you for pointing out that in a pipeline, 
**you should not forget to specify the version numbers of the plugins you call, even if its a one liner.**

**Comment by ajarmoniuk** [comment] 2022-12-19 17:35
Is that a bug report?

**Comment by ajarmoniuk** [comment] 2022-12-19 17:46
By the way, that reactor structure is not that uncommon. Sorry about the missed nights.

**Comment by slawekjaranowski** [comment] 2022-12-19 18:08
@uvwild Thanks for your share. 

That is a good practice to pointing **version** of **all** component which you use in order to have a reproducible builds.

As you see, as soon as issue was reported by others, it was fixed and bug fix release was done - #848

All improvements can introduce new bugs it is a usual - everybody can help, testing release candidate and so on.
We can't stop our work due to afraid of new bugs.

Release of `2.14.0` was announced two weeks before release - so you can check next version early #839

You can follow next release for `2.14.2` - it will be in a few days  - #864

I'm open for proposition how can we help you in similar situation.

**Closed** 2022-12-20 15:47 UTC
