### ISSUE TITLE
NPE and wrong encoding for umlauts

### ISSUE THREAD

**Issue by BelliFCap** [mojohaus/versions#931] opened 2023-03-14 08:23 UTC
Hi,

i am using org.codehaus.mojo:versions-maven-plugin in latest version (2.15.0) for updating multiple poms in my project.
Note: When I switch back to version 2.14.2 everything works fine.
Now there are two issues:

**1.** The umlauts in the poms are in wrong encoding after updating:
diff:
       Hinzugefügt
-> HinzugefÃ¼gt

**2.** For one pom I get a NPE with these logs:

[ERROR] Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version (default-cli) on project migration: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version failed.: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version (default-cli) on project migration: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version failed.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.codehaus.mojo:versions-maven-plugin:2.15.0:use-dep-version failed.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:148)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: java.lang.NullPointerException
    at org.codehaus.plexus.util.StringUtils.deleteWhitespace (StringUtils.java:147)
    at org.codehaus.mojo.versions.api.PomHelper.setDependencyVersion (PomHelper.java:565)
    at org.codehaus.mojo.versions.AbstractVersionsDependencyUpdaterMojo.updateDependencyVersion (AbstractVersionsDependencyUpdaterMojo.java:536)
    at org.codehaus.mojo.versions.UseDepVersionMojo.useDepVersion (UseDepVersionMojo.java:366)
    at org.codehaus.mojo.versions.UseDepVersionMojo.processModel (UseDepVersionMojo.java:201)
    at org.codehaus.mojo.versions.UseDepVersionMojo.execute (UseDepVersionMojo.java:156)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

**Comment by ajarmoniuk** [comment] 2023-03-14 11:31
The NPE issue is fixed in a recently merged PR. Regarding the umlauts, could you please attach a simplified POM which reproduces the issue? It's an issue with encoding, but I wasn't able to reproduce it.

**Comment by BelliFCap** [comment] 2023-03-14 12:21
It's enough to put a comment in pom like this:

**Comment by ajarmoniuk** [comment] 2023-03-14 12:24
I tried doing that before asking that question and could not reproduce the issue.

Are you using a specific encoding in the preamble by any chance?

**Comment by BelliFCap** [comment] 2023-03-14 12:26
The encoding of the pom is UTF-8.

**Comment by ajarmoniuk** [comment] 2023-03-14 12:44
Cannot reproduce.

Test files:

```xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>test-group</groupId>
  <artifactId>test-artifact</artifactId>
  <version>DEVELOP-SNAPSHOT</version>

  <description>Wörter mit Umlauten</description>
  <!-- Vorläufige Container für Tests -->

  <dependencies>
    <dependency>
      <groupId>localhost</groupId>
      <artifactId>dummy-api</artifactId>
      <version>1.0</version>
    </dependency>
  </dependencies>
</project>
```

```properties
invoker.goals = ${project.groupId}:${project.artifactId}:2.15.0:use-dep-version
invoker.mavenOpts = -Dincludes=localhost -DdepVersion=1.0.1
```

```groovy
import groovy.xml.XmlSlurper

def project = new XmlSlurper().parse( new File( basedir, 'pom.xml' ) )
assert project.dependencies.dependency.version == '1.0.1'
assert project.description == 'Wörter mit Umlauten'
```

Test passeed.

Output:

```xml
<?xml version="1.0" encoding="utf-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>test-group</groupId>
  <artifactId>test-artifact</artifactId>
  <version>DEVELOP-SNAPSHOT</version>

  <description>Wörter mit Umlauten</description>
  <!-- Vorläufige Container für Tests -->

  <dependencies>
    <dependency>
      <groupId>localhost</groupId>
      <artifactId>dummy-api</artifactId>
      <version>1.0.1</version>
    </dependency>
  </dependencies>
</project>
```

**Comment by x0b** [comment] 2023-03-14 14:01
I'm experiencing the same issue with umlauts. Reproduction example: https://github.com/x0b/mojohaus-versions-repro/tree/master/fooapp

Running with a build from the current master
```sh
$ mvn org.codehaus.mojo:versions-maven-plugin:2.15.1-SNAPSHOT:use-dep-version -Dincludes=org.projectlombok:lombok -DdepVersion=1.18.26 -DgenerateBackupPoms=false

$ git diff
```
```diff
diff --git a/fooapp/pom.xml b/fooapp/pom.xml
index c3da863..acdb295 100644
--- a/fooapp/pom.xml
+++ b/fooapp/pom.xml
@@ -22,7 +22,7 @@

     <dependencyManagement>
         <dependencies>
-            <!-- Löts öf Germän umlauts-->
+            <!-- LÃ¶ts Ã¶f GermÃ¤n umlauts-->
             <dependency>
                 <groupId>org.testcontainers</groupId>
                 <artifactId>testcontainers</artifactId>
@@ -36,7 +36,7 @@
         <dependency>
             <groupId>org.projectlombok</groupId>
             <artifactId>lombok</artifactId>
-            <version>1.18.24</version>
+            <version>1.18.26</version>
        </dependency>
     </dependencies>
```

**Comment by ajarmoniuk** [comment] 2023-03-14 15:42
Thanks for that.

I guess this must depend on the environment. I still can't reproduce the issue using your project.

**Comment by x0b** [comment] 2023-03-14 16:07
Not really, but you are right about the environment: it is using the encoding from environment, instead of the encoding as specified in the pom file.

The issue doesn't occur when the environment is set to UTF-8:
```bash
$ env JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8 mvn org.codehaus.mojo:versions-maven-plugin:2.15.1-SNAPSHOT:use-dep-version -Dincludes=org.projectlombok:lombok -DdepVersion=1.18.26 -DgenerateBackupPoms=false
```

But when not set or set to Cp1252, the characters get mangled:
```bash
$ env JAVA_TOOL_OPTIONS=-Dfile.encoding=windows-1252 mvn org.codehaus.mojo:versions-maven-plugin:2.15.1-SNAPSHOT:use-dep-version -Dincludes=org.projectlombok:lombok -DdepVersion=1.18.26 -DgenerateBackupPoms=false
```

**Comment by ajarmoniuk** [comment] 2023-03-14 16:11
Yes, indeed. I finally managed to reproduce a similar issue setting -Dfile.encoding to a different value. 

> Edit: I've re-checked on version 1.14.2, both variants do not cause the issue. So that really changed with 1.15.x.

Thanks, that helps narrow the issue down.

**Closed** 2023-05-14 18:08 UTC
Labels: bug
