### ISSUE TITLE
Plugin does not evaluate GroupId / ArtifactId property variables

### ISSUE THREAD

**Issue by Tholian** [mojohaus/versions#1001] opened 2023-09-07 08:25 UTC
If th groupId of an dependency is defined in a property and this property-variable is used in the dependency the execution of `mvn versions:display-dependency-updates` shows some problems.

eg. following pom.xml snippet

```xml
...
<properties>
	<archunitGroupId>com.tngtech.archunit</archunitGroupId>
	<archunit.version>1.1.0</archunit.version>
</properties>

...

<dependency>
	<groupId>${archunitGroupId}</groupId>
	<artifactId>archunit</artifactId>
	<version>${archunit.version}</version>
</dependency>
```

will lead to this console output:

[INFO] --- versions-maven-plugin:2.16.0:display-dependency-updates (default-cli) @ myProject---
Downloading from nexus: http://myNexusRepo/nexus/content/groups/public/$%7BarchunitGroupId%7D/archunit/maven-metadata.xml

As you can see, the GroupId was not correctly determined.

Excpected behaviour is a correct usage of variables even for groupId an artifactId.

**Comment by ajarmoniuk** [comment] 2023-09-08 04:42
I'll look into it.

**Comment by ajarmoniuk** [comment] 2023-09-08 05:24
Strangely enough, so far I haven't been able to reproduce the issue.

I tried this test scenario:

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>localhost</groupId>
    <artifactId>it-display-dependency-updates-issue-1001-groupid</artifactId>
    <version>1.0</version>
    <packaging>pom</packaging>

    <description>groupId is expressed via a Maven property</description>

    <properties>
        <dep.groupId>localhost</dep.groupId>
        <dep.version>1.0</dep.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>${dep.groupId}</groupId>
            <artifactId>dummy-api</artifactId>
            <version>${dep.version}</version>
        </dependency>
    </dependencies>
</project>
```

```
invoker.goals = ${project.groupId}:${project.artifactId}:${project.version}:display-dependency-updates
invoker.mavenOpts = -Dversions.outputFile=./output.txt -DoutputEncoding=UTF-8
```

```groovy
def output = new File(basedir, "output.txt").text
assert output =~ /\Qlocalhost:dummy-api\E\s*\.*\s*\Q1.0\E\s+->\s+\Q3.0\E\b/
```

and it passes with the relevant log lines:

```
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   localhost:dummy-api ....................................... 1.0 -> 3.0
[INFO] 
```

**Comment by ajarmoniuk** [comment] 2023-09-08 05:30
It looks like this does work with 2.16.0. Could you please isolate a test project which does verify the issue?

**Comment by ajarmoniuk** [comment] 2023-09-08 05:45
@slawekjaranowski do you think we should merge this it in even if this turns out to be working fine, just as an additional safety check?

**Comment by slawekjaranowski** [comment] 2023-09-10 07:58
@Tholian - can you help a reproduce issue?, as you see we can not reproduce it
Without reproduce example, I will close it.

@ajarmoniuk - we can add simple IT to confirm case

**Closed** 2023-09-10 09:11 UTC
Labels: bug

**Comment by slawekjaranowski** [comment] 2023-09-10 09:15
@Tholian we add a test to confirm that working as expected
If you have another case please let us know - how to reproduce

**Comment by Tholian** [comment] 2023-09-19 09:35
Hi, I have tried to set up a test project as an example of the behavior I have seen. But indeed this is working fine.
I don't get the real difference to my life working project where I can spot that issue.

I will try to figure out what causes this misbehavior.
Thank you so far.
